/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegraphique;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class login extends javax.swing.JFrame {
Vector<ob_monture> VecMont;
Vector<ob_verre> VecVer;
Vector<ob_lentille> VecLent;
Vector<ob_vente> VecVent;
Vector<ob_message> Vecmes;


DefaultTableModel tableModel2 = new DefaultTableModel();
DefaultTableModel tableModel = new DefaultTableModel();
DefaultTableModel tableModel3 = new DefaultTableModel();
DefaultTableModel tableModel4 = new DefaultTableModel();
DefaultTableModel tableModel5 = new DefaultTableModel();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        int count=tableModel.getRowCount();
        int j=0;
       while(j<count){
            
        tableModel.removeRow(0);
           j++;
        
        
        }
     jTabbedPane5.setSelectedIndex(0);
         
        
      VecMont=ob_monture.AfficherOb();
          
        //"id", "Reference", "taille A", "taille pont","taille Bras","Couleur"
     for(int i=0;i<VecMont.size();i++){
                
           ob_monture ob=VecMont.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.type);
           v.addElement(ob.reference);
           v.addElement(ob.taille_A);
           v.addElement(ob.taille_pont);
           v.addElement(ob.taille_bras);
           v.addElement(ob.couleur);
           v.addElement(ob.prix);
           v.addElement(ob.contite);
           v.addElement(ob.image);
           
         tableModel.addRow(v);
        
      
        }
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        montures = new javax.swing.JButton();
        verres = new javax.swing.JButton();
        lentilles = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new DefaultTableModel(new String [] {
            "id","Type", "Reference", "taille A", "taille pont","taille Bras","Couleur","Prix","Quantité","image"
        },0);
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModel2 = new DefaultTableModel(new String [] {
            "id","Type", "Indice refraction", "dioptrie", "teinte","traitement","Prix","Quantité","Image"
        },0);
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableModel3 = new DefaultTableModel(new String [] {
            "id","Dioptrie", "Rayon", "Diametre", "Couleur","Marque","Prix","Quantité","Image"
        },0);
        jTable3 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableModel4 = new DefaultTableModel(new String [] {
            "id","Nom", "Numéro", "Numéro de la commande"
        },0);
        jTable4 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableModel5 = new DefaultTableModel(new String [] {
            "id","Nom", "Email", "Le message"
        },0);
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        jPanel7.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel7.setMinimumSize(new java.awt.Dimension(1080, 620));
        jPanel7.setPreferredSize(new java.awt.Dimension(1080, 620));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Optique");
        jLabel11.setToolTipText("");

        jLabel32.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 204));
        jLabel32.setText("Lunette");
        jLabel32.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(384, 384, 384))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel11))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        montures.setBackground(new java.awt.Color(0, 153, 153));
        montures.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        montures.setForeground(new java.awt.Color(255, 255, 255));
        montures.setText("Montures");
        montures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        montures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monturesMouseClicked(evt);
            }
        });
        montures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monturesActionPerformed(evt);
            }
        });

        verres.setBackground(new java.awt.Color(0, 153, 153));
        verres.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        verres.setForeground(new java.awt.Color(255, 255, 255));
        verres.setText("Verres");
        verres.setToolTipText("");
        verres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verresActionPerformed(evt);
            }
        });

        lentilles.setBackground(new java.awt.Color(0, 153, 153));
        lentilles.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lentilles.setForeground(new java.awt.Color(255, 255, 255));
        lentilles.setText("Lentilles");
        lentilles.setToolTipText("");
        lentilles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lentilles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lentillesActionPerformed(evt);
            }
        });

        jPanel29.setBackground(new java.awt.Color(0, 51, 51));

        jButton18.setBackground(new java.awt.Color(0, 204, 204));
        jButton18.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 102, 102));
        jButton18.setText("Ajouter un produit");
        jButton18.setToolTipText("");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 204, 204));
        jButton16.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 102, 102));
        jButton16.setText("Consulter les commandes");
        jButton16.setToolTipText("");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 204, 204));
        jButton17.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 102, 102));
        jButton17.setText("Consulter les messages");
        jButton17.setToolTipText("");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jButton21.setBackground(new java.awt.Color(153, 255, 255));
        jButton21.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 102, 102));
        jButton21.setText("Quitter");
        jButton21.setToolTipText("");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lentilles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(montures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(montures, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lentilles, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 610));

        jTabbedPane5.setForeground(new java.awt.Color(0, 153, 153));
        jTabbedPane5.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N

        jTable1.setModel(
            tableModel
        );
        jTable1.setDropMode(javax.swing.DropMode.INSERT);
        jTable1.setGridColor(new java.awt.Color(0, 153, 153));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("Supprimer");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 255));
        jButton6.setText("Modifier");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jTabbedPane5.addTab("monture", jPanel3);

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 255, 255));
        jButton7.setText("Supprimer");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 153, 153));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 255, 255));
        jButton8.setText("Modifier");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable2.setModel(tableModel2);
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Verres", jPanel4);

        jPanel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel5PropertyChange(evt);
            }
        });

        jTable3.setModel(tableModel3);
        jTable3.setDropMode(javax.swing.DropMode.INSERT);
        jTable3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable3PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 255, 255));
        jButton9.setText("Modifier");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 153, 153));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 255));
        jButton10.setText("Supprimer");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Lentilles", jPanel5);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter verre");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ajouter lentille");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ajouter monture");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(270, 270, 270))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Achat", jPanel6);

        jTable4.setModel(tableModel4);
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Vente", jPanel27);

        jTable5.setModel(tableModel5);
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab6", jPanel8);

        jPanel7.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 870, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monturesActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane5.setSelectedIndex(0);
       int count=tableModel.getRowCount();
       int j=0;
       while(j<count){
            
        tableModel.removeRow(0);
           j++;
        
        
        }
      VecMont=ob_monture.AfficherOb();
          
        //"id", "Reference", "taille A", "taille pont","taille Bras","Couleur"
       for(int i=0;i<VecMont.size();i++){
                
           ob_monture ob=VecMont.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.type);
           v.addElement(ob.reference);
           v.addElement(ob.taille_A);
           v.addElement(ob.taille_pont);
           v.addElement(ob.taille_bras);
           v.addElement(ob.couleur);
           v.addElement(ob.prix);
           v.addElement(ob.contite);
           v.addElement(ob.image);
           tableModel.addRow(v);
        
      
        }
        
    }//GEN-LAST:event_monturesActionPerformed

    private void verresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verresActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(1);
        int count=tableModel2.getRowCount();
       int j=0;
       while(j<count){
            
        tableModel2.removeRow(0);
           j++;
        
        
        }
      VecVer=ob_verre.AfficherOb();
          
        //"id", "Reference", "taille A", "taille pont","taille Bras","Couleur"
       for(int i=0;i<VecVer.size();i++){
                
           ob_verre ob=VecVer.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.type);
           v.addElement(ob.indice_refraction);
           v.addElement(ob.dioptrie);
           v.addElement(ob.teinte);
           v.addElement(ob.traitment);
           v.addElement(ob.prix);
           v.addElement(ob.contite);
           v.addElement(ob.image);
         tableModel2.addRow(v);
        
       }
        
    }//GEN-LAST:event_verresActionPerformed

    private void lentillesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lentillesActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(2);
        int count=tableModel3.getRowCount();
       int j=0;
       while(j<count){
            
        tableModel3.removeRow(0);
           j++;
        
        
        }
      VecLent=ob_lentille.AfficherOb();
          
        //"id","Dioptrie", "Rayon", "Diametre", "Couleur","Marque","Prix","Quantité"
       for(int i=0;i<VecLent.size();i++){
                
           ob_lentille ob=VecLent.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.dioptrie);
           v.addElement(ob.rayon);
           v.addElement(ob.diametre);
           v.addElement(ob.couleur);
           v.addElement(ob.marque_labo);
           v.addElement(ob.prix);
           v.addElement(ob.contite);
           v.addElement(ob.image);
         tableModel3.addRow(v);
        
       }
    }//GEN-LAST:event_lentillesActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(3);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:*
        jTabbedPane5.setSelectedIndex(4);
        int count=tableModel4.getRowCount();
       int j=0;
       while(j<count){
            
        tableModel4.removeRow(0);
           j++;
        
        
        }
      VecVent=ob_vente.AfficherOb();
          
        //"id", "Reference", "taille A", "taille pont","taille Bras","Couleur"
       for(int i=0;i<VecVent.size();i++){
                
           ob_vente ob=VecVent.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.name);
           v.addElement(ob.numero);
           v.addElement(ob.commande);
           tableModel4.addRow(v);
        
      
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ajouter_verre(null,true).show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ajouter_lentille(null,true).show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new ajouter_monture(null,true).show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       //id,type,indice_refraction,dioptrie,teinte,traitement,prix,contite,image
        int select=jTable2.getSelectedRow();
        ob_verre ob = new ob_verre();
        ob.id =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 0)));
        ob.type = String.valueOf( tableModel2.getValueAt(select, 1));
        ob.indice_refraction =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 2)));
        ob.dioptrie =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 3)));
        ob.teinte = String.valueOf( tableModel2.getValueAt(select, 4));
        ob.traitment = String.valueOf( tableModel2.getValueAt(select, 5));
        ob.prix =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 6)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 7)));
        ob.image = String.valueOf( tableModel2.getValueAt(select, 8));
        ob.Modiffierob();
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int select=jTable1.getSelectedRow();
        ob_monture ob = new ob_monture();
        ob.Supprimer(select);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int select=jTable2.getSelectedRow();
        ob_verre ob = new ob_verre();
        ob.Supprimer(select);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //"id","Type", "Reference", "taille A", "taille pont","taille Bras","Couleur","Quantité","Prix"
        int select=jTable1.getSelectedRow();
        ob_monture ob = new ob_monture();
        ob.id =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 0)));
        ob.type = String.valueOf( tableModel.getValueAt(select, 1));
        ob.reference = String.valueOf( tableModel.getValueAt(select, 2));
        ob.taille_A =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 3)));
        ob.taille_pont =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 4)));
        ob.taille_bras =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 5)));
        ob.couleur = String.valueOf( tableModel.getValueAt(select, 6));
        ob.prix =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 7)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 8)));
        ob.image = String.valueOf( tableModel.getValueAt(select, 9));
        ob.Modiffierob();
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int select=jTable3.getSelectedRow();
        ob_lentille ob = new ob_lentille();
        //id,dioptrie,rayon,diametre,couleur,marque_labo,prix,contite,image
        ob.id =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 0)));
        ob.dioptrie =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 1)));
        ob.rayon =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 2)));
        ob.diametre =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 3)));
        ob.couleur = String.valueOf( tableModel3.getValueAt(select, 4));
        ob.marque_labo = String.valueOf( tableModel3.getValueAt(select, 5));
        ob.prix =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 6)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 7)));
        ob.image = String.valueOf( tableModel3.getValueAt(select, 8));
        ob.ModiffierOb();
        
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        
        int select=jTable1.getSelectedRow();
        
        if((jTable1.getRowCount()>0)&& (select!=-1 )){
        
        ob_monture ob = new ob_monture();
        ob.id =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 0)));
        ob.type = String.valueOf( tableModel.getValueAt(select, 1));
        ob.reference = String.valueOf( tableModel.getValueAt(select, 2));
        ob.taille_A =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 3)));
        ob.taille_pont =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 4)));
        ob.taille_bras =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 5)));
        ob.couleur = String.valueOf( tableModel.getValueAt(select, 6));
        ob.prix =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 7)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel.getValueAt(select, 8)));
        ob.image =String.valueOf( tableModel.getValueAt(select, 9));
        ob.Modiffierob();
        System.err.println("fffffffffffff");}
        
        
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable2PropertyChange
        // TODO add your handling code here:
        int select=jTable2.getSelectedRow();
        
        if((jTable2.getRowCount()>0)&& (select!=-1 )){
        
        ob_verre ob = new ob_verre();
        ob.id =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 0)));
        ob.type = String.valueOf( tableModel2.getValueAt(select, 1));
        ob.indice_refraction =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 2)));
        ob.dioptrie =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 3)));
        ob.teinte = String.valueOf( tableModel2.getValueAt(select, 4));
        ob.traitment = String.valueOf( tableModel2.getValueAt(select, 5));
        ob.prix =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 6)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel2.getValueAt(select, 7)));
        ob.image = String.valueOf( tableModel2.getValueAt(select, 8));
        ob.Modiffierob();
        System.err.println("fffffffffffff");}
    }//GEN-LAST:event_jTable2PropertyChange

    private void jTable3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable3PropertyChange
        // TODO add your handling code here:
        int select=jTable3.getSelectedRow();
        
        if((jTable3.getRowCount()>0)&& (select!=-1 )){
        ob_lentille ob = new ob_lentille();
        //id,dioptrie,rayon,diametre,couleur,marque_labo,prix,contite,image
        ob.id =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 0)));
        ob.dioptrie =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 1)));
        ob.rayon =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 2)));
        ob.diametre =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 3)));
        ob.couleur = String.valueOf( tableModel3.getValueAt(select, 4));
        ob.marque_labo = String.valueOf( tableModel3.getValueAt(select, 5));
        ob.prix =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 6)));
        ob.contite =Integer.parseInt(String.valueOf( tableModel3.getValueAt(select, 7)));
        ob.image = String.valueOf( tableModel3.getValueAt(select, 8));
        ob.ModiffierOb();
        }
    }//GEN-LAST:event_jTable3PropertyChange

    private void jPanel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel5PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel5PropertyChange

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int select=jTable3.getSelectedRow();
        ob_lentille ob = new ob_lentille();
        ob.Supprimer(select);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void monturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monturesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_monturesMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(5);
        int count=tableModel5.getRowCount();
       int j=0;
       while(j<count){
            
        tableModel5.removeRow(0);
           j++;
        
        
        }
      Vecmes=ob_message.AfficherOb();
          
        //"id", "Reference", "taille A", "taille pont","taille Bras","Couleur"
       for(int i=0;i<Vecmes.size();i++){
                
           ob_message ob=Vecmes.elementAt(i);
           
           Vector v=new Vector();
           
           v.addElement(ob.id);
           v.addElement(ob.name);
           v.addElement(ob.email);
           v.addElement(ob.message);
           tableModel5.addRow(v);
        
      
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton lentilles;
    private javax.swing.JButton montures;
    private javax.swing.JButton verres;
    // End of variables declaration//GEN-END:variables

    private static class NewJDialog {

        public NewJDialog() {
        }
    }
}
